# functions that help with plotting

import numpy as np
from scipy.stats import zscore
import matplotlib.ticker as ticker
import seaborn as sns
import statsmodels.api as sm
import matplotlib.pyplot as plt
from functions.util_functions import compute_median_iqr, compute_test_statistic

medianprops = dict(linestyle='-', linewidth=1, color='k')
whiskerprops = dict(linewidth=0.5)
boxprops = dict(alpha=0.7)
colors = ["#80cdc1",'#de77ae',"#018571", "#dfc27d",'#d492c8','#AA4499','#808080',"#77AADD","#3576b8"]
# b082a8
sns.set_palette(sns.color_palette(colors))

def robust_regplot(df,x,y,ax,var_x_z,color_index=0,line_color_index=0, legend_txt=None, endog=None, exog=None,):
    """
        Plot a robust regression line and optionally return regression statistics.

        A robust regression line is plotted using ``seaborn.regplot`` with
        ``robust=True``. If ``endog`` and ``exog`` are provided, a robust linear
        model (RLM) using Huber's T norm is additionally fitted with
        ``statsmodels``. The coefficient, p-value, and t-statistic corresponding
        to ``var_x_z`` are returned.

        Parameters
        ----------
        df : pandas.DataFrame
            DataFrame containing the variables to plot.
        x : str
            Name of the predictor column in 'df'.
        y : str
            Name of the outcome column in 'df'.
        ax : matplotlib.axes.Axes
            Matplotlib axes on which to plot the regression.
        var_x_z : str
            Name of the predictor whose regression coefficient, p-value, and
            t-statistic should be returned after applying the regression.
        color_index : int, default=0
            Index of the color used for the scatter points in ``colors``.
        line_color_index : int, default=0
            Index of the color used for the regression line in ``colors``.
        legend_txt : str or None, default=None
            Label assigned to the regression line for use in the legend.
        endog : np.ndarray or None, default=None
            Endogenous (dependent) variable used to fit the robust linear model.
            If ``None``, no separate RLM is fitted.
        exog : np.ndarray or None, default=None
            Exogenous (predictor) variables used to fit the robust linear model.
            If ``None``, no separate RLM is fitted.

        Returns
        -------
        r : float or None
            Estimated regression coefficient for ``var_x_z``, rounded to two
            decimal places.
        p : float or None
            p-value for the coefficient of ``var_x_z``, rounded to two decimal
            places.
        t : float or None
            t-statistic for the coefficient of ``var_x_z``, rounded to two
            decimal places.

        Notes
        -----
        The plotted regression line is generated by ``seaborn.regplot`` using
        robust regression, while the returned statistics are obtained from a
        separate ``statsmodels.RLM`` fit using robust Huber's T norm.
        """

    sns.regplot(x=df[x].astype('float'), y=df[y].astype('float'),  # color='#3576b8'
                color=colors[line_color_index], robust=True, ax=ax,  # label=legend_txt
                scatter_kws=dict(alpha=0.3, s=10, edgecolor="none", color=colors[color_index]),
                line_kws=dict(linewidth=2, label=legend_txt));

    # Fit robust model if endog and exog are not empty
    if endog is not None and exog is not None:
        rlm_model = sm.RLM(endog, exog, M=sm.robust.norms.HuberT())

        rlm_results = rlm_model.fit()
        r = round(rlm_results.params[var_x_z], 2)
        p = round(rlm_results.pvalues[var_x_z], 2)
        t = round(rlm_results.tvalues[var_x_z], 2)

        # return regression coefficients
        return r, p, t
    else:
        # If no endog and exog provided, return None
        return None, None, None

def plot_boxplots(df,x,y,ax,order=None,ylabel=None,xlabel=None,fontsize=7):
    """
        Plot boxplots with overlaid individual data points.

        Parameters
        ----------
        df : pandas.DataFrame
            DataFrame containing the variables to plot.
        x : str
            Name of the column in ``df`` containing the variable
            displayed on the x-axis.
        y : str
            Name of the column in ``df`` containing the variable
            displayed on the y-axis.
        ax : matplotlib.axes.Axes
            Matplotlib axes on which to plot the boxplots and individual data
            points.
        order : list of str or None, default=None
            Order in which the categorical levels should be displayed. If
            ``None``, the order is determined by seaborn.
        ylabel : str or None, default=None
            Label for the y-axis.
        xlabel : str or None, default=None
            Label for the x-axis.
        fontsize : int, default=7
            Font size used for the axis labels.

        Returns
        -------
        None
        """

    sns.boxplot(x=x, y=y, data=df, order=order, fliersize=0,
                linewidth=0.5, ax=ax, width=0.5,
                medianprops=medianprops,
                meanprops={'marker': 'o', 'markerfacecolor': 'red', 'markeredgecolor': 'black', 'markersize': 10},
                boxprops=boxprops, zorder=7, )

    sns.stripplot(x=x, y=y, data=df, order=order, jitter=0.05,
                  alpha=0.3, size=3, zorder=0, ax=ax)

    ax.set_ylabel(ylabel, fontsize=fontsize)
    ax.set_xlabel(xlabel, fontsize=fontsize)

def boxplots_lab(df,ax,fontsize=7,abbr='EE',ylabel='Estimation Error', stat='ttest_rel'):
    """
      Plot boxplots comparing screams and shocks in the laboratory study.

      The function plots boxplots with overlaid individual observations for
      the two experimental conditions, computes a statistical comparison
      between conditions, and annotates the plot with the resulting p-value.
      Median and interquartile range (IQR) values are also calculated and
      returned.

      Parameters
      ----------
      df : pandas.DataFrame
          DataFrame containing the laboratory study data. The relevant
          variables are expected to be named using ``abbr`` followed by
          ``"_B0"`` and ``"_B1"``.
      ax : matplotlib.axes.Axes
          Matplotlib axes on which to plot the boxplots.
      fontsize : int, default=7
          Font size used for the plot title, axis labels, and tick labels.
      abbr : str, default="EE"
          Prefix identifying the variable to plot. The function expects
          columns ``abbr + "_B0"`` and ``abbr + "_B1"`` in ``df``.
      ylabel : str, default="Estimation Error"
          Label for the y-axis.
      stat : str, default="ttest_rel"
          Statistical test used to compare the two conditions. Passed to
          ``compute_test_statistic``.

      Returns
      -------
      r : float
          Test statistic from the statistical comparison.
      p : float
          P-value from the statistical comparison.
      dof : float
          Degrees of freedom for the statistical test. Only returned when
          ``stat`` is not ``"mannU"``.
      n1 : int
          Sample size for the first condition. Only returned when ``stat`` is
          not ``"mannU"``.
      n2 : int
          Sample size for the second condition. Only returned when ``stat`` is
          not ``"mannU"``.
      median_scream : float
          Median value for the screams condition (``abbr + "_B0"``).
      scream_iqr : float
          Interquartile range for the screams condition.
      median_shock : float
          Median value for the shocks condition (``abbr + "_B1"``).
      shock_iqr : float
          Interquartile range for the shocks condition.

      Notes
      -----
      The ``"_B0"`` condition is displayed as ``"Screams"`` and the
      ``"_B1"`` condition is displayed as ``"Shocks"``.
      """

    df_relevant = df[[abbr + '_B0', abbr + '_B1']]
    df_long = df_relevant.melt(var_name='Block', value_name='Value')

    # Plot boxplots for lab study
    sns.boxplot(data=df_relevant, fliersize=0, linewidth=0.5, ax=ax, width=0.5,
                medianprops=medianprops,
                meanprops={'marker': 'o', 'markerfacecolor': 'red', 'markeredgecolor': 'black', 'markersize': 10},
                boxprops=dict(alpha=.7), zorder=7, )

    sns.stripplot(data=df_relevant, jitter=0.05, alpha=0.3, size=3, zorder=0, ax=ax)

    # Compute test statistics
    r, p, dof, n1, n2 = compute_test_statistic(df_long, group_col='Block', value_col='Value', group1=abbr + '_B0', group2=abbr + '_B1', test=stat)

    # set title
    title = "$\it{p}$ = " + str(round(p, 2))
    ax.set_title(title, fontsize=fontsize)

    # set x and y limits
    ax.set_xticklabels(['Screams', 'Shocks'])
    ax.set_ylabel(ylabel, fontsize=fontsize)
    min = df_relevant.min().min()
    max = df_relevant.max().max()
    ax.set_ylim([min - 0.5, max + 0.5])
    ax.xaxis.set_tick_params(labelsize=fontsize)
    ax.yaxis.set_tick_params(labelsize=fontsize)

    # extract median and iqr vals
    median_scream, scream_iqr = compute_median_iqr(df[abbr + '_B0'])
    median_shock, shock_iqr = compute_median_iqr(df[abbr + '_B1'])

    if (stat == 'mannU'):
        return r, p, median_scream, scream_iqr, median_shock, shock_iqr

    else:
        return r, p, dof, n1, n2, median_scream, scream_iqr, median_shock, shock_iqr



def plot_x_vs_y_robust(df,x,y,ax,legend_txt=None,xlabel=None,ylabel=None,title=False,tstat=False,fontsize=7,color_index=0,line_color_index=0):
    """
        Plot a robust regression of y against x while controlling for age and gender.

        The function removes participants with gender code (``3``) since there aren't enough non-binary participants,
        z-scores age and the x and y variables, and fits a robust linear model
        predicting the standardized outcome from the standardized predictor,age, and gender.
        A robust regression line is plotted using :func:`robust_regplot`.

        Parameters
        ----------
        df : pandas.DataFrame
            DataFrame containing the predictor, outcome, age, and gender variables.
        x : str
            Name of the predictor column in ``df``.
        y : str
            Name of the outcome column in ``df``.
        ax : matplotlib.axes.Axes
            Matplotlib axes on which to plot the regression.
        legend_txt : str or None, default=None
            Label for the regression line in the plot legend.
        xlabel : str or None, default=None
            Label for the x-axis.
        ylabel : str or None, default=None
            Label for the y-axis.
        title : bool, default=False
            If ``True``, display the regression coefficient and p-value as the
            plot title.
        tstat : bool, default=False
            If ``True``, return the t-statistic in addition to the regression
            coefficient and p-value.
        fontsize : int, default=7
            Font size used for axis labels, tick labels, and the optional title.
        color_index : int, default=0
            Index of the color used for the scatter points in ``colors``.
        line_color_index : int, default=0
            Index of the color used for the regression line in ``colors``.

        Returns
        -------
        r : float
            Robust regression coefficient for the association between ``x`` and
            ``y``, controlling for age and gender.
        p : float
            P-value associated with the regression coefficient for ``x``.
        t : float, optional
            T-statistic associated with the regression coefficient for ``x``.
            Returned only when ``tstat=True``.

        """
    df = df[df['Gender'] != 3]
    df['Age_z'] = zscore(df['Age'])
    df['var_x_z'] = zscore(df[x])
    df['var_y_z'] = zscore(df[y])

    var_x_z = 'var_x_z'

    exog = df[['var_x_z','Age_z','Gender']]
    exog = sm.add_constant(exog)
    endog = df['var_y_z']

    # Plot a regression line with robust regression
    r,p,t = robust_regplot(df,x,y,ax,var_x_z,color_index,line_color_index,legend_txt,endog,exog)

    if (title):
        title_curr =  '$\it{r}$ = ' + str(r) + ' , $\it{p}$ = ' + str(p)
        ax.set_title(title_curr, fontsize=fontsize)

    min = np.min(df[x])
    max = np.max(df[x])
    ax.set_xlim([min-0.7, max+0.5])
    ax.set_ylabel(ylabel, fontsize=fontsize)
    ax.set_xlabel(xlabel, fontsize=fontsize)
    ax.yaxis.set_major_locator(ticker.MaxNLocator(nbins=5))
    ax.xaxis.set_tick_params(labelsize=fontsize)
    ax.yaxis.set_tick_params(labelsize=fontsize)

    if (tstat):
        return (r,p, t)
    else:
        return (r,p)


def plot_x_vs_y_FactorScores_robust(df,x,y,ax,legend_txt=None,xlabel=None,ylabel=None,title=False,tstat=False,fontsize=7,color_index=0,line_color_index=0):
    """
        Plot a robust regression of a factor score given by x against parameter of interest y.
        Also calculates regression of variable of interest with all the factor scores, and age and gender as covariates.

        Parameters
        ----------
        df : pandas.DataFrame
            DataFrame containing the predictor, outcome, factor scores, age,
            and gender variables.
        x : str
            Name of the factor-score column in ``df`` to be plotted as the
            predictor. If the column name contains a period, the period is
            removed when constructing the standardized variable name.
        y : str
            Name of the outcome column in ``df``.
        ax : matplotlib.axes.Axes
            Matplotlib axes on which to plot the regression.
        legend_txt : str or None, default=None
            Label for the regression line in the plot legend.
        xlabel : str or None, default=None
            Label for the x-axis.
        ylabel : str or None, default=None
            Label for the y-axis.
        title : bool, default=False
            If ``True``, display the regression coefficient and p-value as the
            plot title.
        tstat : bool, default=False
            If ``True``, return the t-statistic in addition to the regression
            coefficient and p-value.
        fontsize : int, default=7
            Font size used for axis labels, tick labels, and the optional title.
        color_index : int, default=0
            Index of the color used for the scatter points in ``colors``.
        line_color_index : int, default=0
            Index of the color used for the regression line in ``colors``.

        Returns
        -------
        r : float
            Robust regression coefficient for the selected factor score,
            controlling for the other factor scores, age, and gender.
        p : float
            P-value associated with the regression coefficient for the selected
            factor score.
        t : float, optional
            T-statistic associated with the regression coefficient for the
            selected factor score. Returned only when ``tstat=True``.

        """

    df = df[df['Gender']!=3]
    df.loc[:, 'Age_z'] = zscore(df['Age'])
    df.loc[:, 'g_z'] = zscore(df['g'])
    df.loc[:, 'F1_z'] = zscore(df['F1.'])
    df.loc[:, 'F2_z'] = zscore(df['F2.'])
    df.loc[:, 'var_y_z'] = zscore(df[y])

    # take out the . if it exists in x name
    x_temp = x.replace('.','')
    var_x_z = x_temp + '_z'

    exog = df[['g_z','F1_z','F2_z','Age_z','Gender']]
    exog = sm.add_constant(exog)
    endog = df['var_y_z']

    # Plot a regression line with robust regression
    r, p, t = robust_regplot(df, x, y, ax, var_x_z, color_index, line_color_index, legend_txt, endog, exog)

    if (title):
        title_curr =  "$\it{r}$ = " + str(r) +', ' + "$\it{p}$ = " + str(p)
        ax.set_title(title_curr, fontsize=fontsize)

    min = np.min(df[x])
    max = np.max(df[x])
    ax.set_xlim([min-0.5, max+0.5])
    ax.set_ylabel(ylabel, fontsize=fontsize)
    ax.set_xlabel(xlabel, fontsize=fontsize)
    ax.yaxis.set_major_locator(ticker.MaxNLocator(nbins=4))
    ax.xaxis.set_major_locator(ticker.MaxNLocator(nbins=3))
    ax.xaxis.set_tick_params(labelsize=fontsize)
    ax.yaxis.set_tick_params(labelsize=fontsize)

    if (tstat):
        return (r,p, t)
    else:
        return (r,p)


def plot_descriptive_boxplots(df,x,y,ax,ylabel=None,xlabel=None,title=False,order=None,fontsize=7,min_val=None,max_val=None, stat='ttest_ind'): #stats=mannU or ttest_ind or ttest_rel

    """
        Plot boxplots comparing low- and high-internalizing groups.

        The function plots boxplots that compare the ``Low`` and ``High`` groups for the specified descriptive parameter
         and calculates the median and interquartile range (IQR) for each group.

        Parameters
        ----------
        df : pandas.DataFrame
            DataFrame containing the grouping and outcome variables.
        x : str
            Name of the categorical grouping column in ``df``. The column must
            contain ``"Low"`` and ``"High"`` group labels.
        y : str
            Name of the descriptive parameter of interest in ``df``.
        ax : matplotlib.axes.Axes
            Matplotlib axes on which to plot the boxplots.
        ylabel : str or None, default=None
            Label for the y-axis.
        xlabel : str or None, default=None
            Label for the x-axis.
        title : bool, default=False
            If ``True``, display the p-value from the statistical test as the
            plot title.
        order : list of str or None, default=None
            Order in which the categorical groups are displayed. If ``None``,
            the order is determined by seaborn.
        fontsize : int, default=7
            Font size used for axis labels, tick labels, and the optional title.
        min_val : float or None, default=None
            Lower limit of the y-axis. If ``None``, the minimum observed value
            minus 0.5 is used.
        max_val : float or None, default=None
            Upper limit of the y-axis. If ``None``, the maximum observed value
            plus 0.5 is used.
        stat : {"ttest_ind", "mannU", "ttest_rel"}, default="ttest_ind"
            Statistical test used to compare the ``Low`` and ``High`` groups.
            The value is passed to ``compute_test_statistic``.

        Returns
        -------
        r : float
            Test statistic from the specified statistical test.
        p : float
            p-value from the specified statistical test.
        dof : float
            Degrees of freedom for the test. Returned only when
            ``stat="ttest_ind"``.
        n1 : int
            Sample size of the first group. Returned only when
            ``stat="ttest_ind"``.
        n2 : int
            Sample size of the second group. Returned only when
            ``stat="ttest_ind"``.
        median_Low : float
            Median of the outcome variable for the ``Low`` group.
        median_Low_iqr : float
            Interquartile range of the outcome variable for the ``Low`` group.
        median_High : float
            Median of the outcome variable for the ``High`` group.
        median_High_iqr : float
            Interquartile range of the outcome variable for the ``High`` group.

        """
    plot_boxplots(df,x,y,ax,order=order,ylabel=ylabel,xlabel=xlabel,fontsize=fontsize)

    # Compute test statistics
    r,p,dof,n1,n2 = compute_test_statistic(df,x,y,group1='Low',group2='High',test=stat)

    median_Low, median_Low_iqr = compute_median_iqr(df[df[x] == 'Low'][y])
    median_High, median_High_iqr = compute_median_iqr(df[df[x] == 'High'][y])


    if title:
        title = "$\it{p}$ = " + str(round(p, 2))
        ax.set_title(title, fontsize=fontsize)


    if min_val==None:
        min_val = df[y].min()-0.5

    if max_val==None:
        max_val = df[y].max()+0.5
    ax.set_ylim([min_val, max_val])
    ax.xaxis.set_tick_params(labelsize=fontsize)
    ax.yaxis.set_tick_params(labelsize=fontsize)
    ax.yaxis.set_major_locator(ticker.MaxNLocator(nbins=4))

    if (stat == 'ttest_ind'):
        return r, p, dof, n1, n2, median_Low, median_Low_iqr, median_High, median_High_iqr

    else:
        return (r,p,median_Low,median_Low_iqr,median_High,median_High_iqr)


def plot_EE_across_blocks(EE,ax,fontsize=7,title=None,Legend=False):
    """
        Plot estimation errors across experimental blocks.

        Estimation errors are displayed as boxplots for low- and high-variability
        conditions across four experimental blocks.

        Parameters
        ----------
        EE : pandas.DataFrame
            DataFrame containing estimation error values for each experimental
            block. The following columns are required: ``EE_B0``, ``EE_B1``,
            ``EE_B2``, and ``EE_B3``.
        ax : matplotlib.axes.Axes
            Matplotlib axes on which to plot the boxplots and scatter points.
        fontsize : int, default=7
            Font size used for the title, axis labels, tick labels, and legend.
        title : str or None, default=None
            Title displayed above the plot. If ``None``, no title is displayed.
        Legend : bool, default=False
            If ``True``, display a legend distinguishing the low- and
            high-variability conditions.

        Returns
        -------
        None

        Notes
        -----
        Blocks ``B0`` represents low-variability low HR, ``B1`` represent the low-variability high HR condition,
        ``B2`` represents high variability low HR and ``B3`` represent the high-variability high HR condition.

        """
    ps = [0, 0.5, 2, 2.5]
    data_to_plot = [EE['EE_B0'], EE['EE_B1'], EE['EE_B2'],
                    EE['EE_B3']]

    bp1 = ax.boxplot([EE['EE_B0'], EE['EE_B2']], positions=[0, 2], patch_artist=True,showfliers=False,
                     boxprops=dict(alpha=0.5,facecolor=colors[0], linewidth=0.5),
                     medianprops=medianprops,
                     whiskerprops=whiskerprops,
                     capprops=whiskerprops,
                     flierprops=whiskerprops,

                     )
    bp2 = ax.boxplot([EE['EE_B1'], EE['EE_B3']], positions=[0.5, 2.5],showfliers=False,
                     patch_artist=True,
                     boxprops=dict(alpha=0.5, facecolor=colors[1], linewidth=0.5),
                     medianprops=medianprops,
                     whiskerprops=whiskerprops,
                     capprops=whiskerprops,
                     flierprops=whiskerprops,

                     )

    # Add scatter points with jitter
    for i in range(len(data_to_plot)):
        y = data_to_plot[i]
        # Add some random "jitter" to the x-axis
        x = np.random.normal(ps[i], 0.02, size=len(y))
        ax.scatter(x, y, alpha=0.4, color='#808080',s=3, edgecolors='none')

    if Legend == True:
        ax.legend([bp1["boxes"][0], bp2["boxes"][0]], ['Low', 'High'], loc='upper left',title="Variability",
                  handlelength=1,fontsize=fontsize-1, title_fontsize=fontsize-1)

    ax.set_title(title,fontsize=fontsize, weight='bold')
    ax.set_title(title, fontsize=fontsize)
    ax.set_xlabel('Hazard Rate',fontsize=fontsize)
    ax.set_ylabel('Estimation Error', fontsize=fontsize)
    ax.set_xticks([0.25, 2.25], labels=['Low', 'High'])     # Set new tick labels
    ax.set_ylim([10, 70])
    ax.axhline(0, color='black', linestyle='--')
    ax.xaxis.set_tick_params(labelsize=fontsize)
    ax.yaxis.set_tick_params(labelsize=fontsize)


def FDR_correction_regression(df,endog,exog_array,rlm_out=False):
    """
        Fit robust regressions and apply false discovery rate correction.

        A separate robust linear model is fitted for each dependent variable in
        ``endog`` using the predictors specified in ``exog_array``. Huber's T
        norm is used for the robust regression. P-values are corrected for
        multiple comparisons using the Benjamini-Hochberg false discovery rate
        (FDR) procedure.

        FDR correction is applied both across all regression p-values combined.

        Parameters
        ----------
        df : pandas.DataFrame
            DataFrame containing the dependent and independent variables.
        endog : sequence of str
            Names of the dependent-variable columns in ``df``. A separate
            robust linear regression is fitted for each variable.
        exog_array : sequence of str
            Names of the predictor columns in ``df`` to include in every
            regression.
        rlm_out : bool, default=False
            If ``True``, also return dictionaries containing the regression
            coefficients and t-statistics for each dependent variable.

        Returns
        -------
        p_corrected : numpy.ndarray
            Flattened array of p-values from all regressions after FDR correction,
            rounded to three decimal places.
        p_b1 : float
            FDR-corrected p-value corresponding to index 1 (fixed LR vs General Factor) of the flattened
            p-value array.
        p_b4 : float
            FDR-corrected p-value corresponding to index 7 (adaptive LR vs General Factor) of the flattened
            p-value array.
        rlm_results_dict : dict, optional
            Dictionary mapping each dependent-variable name to its fitted
            regression coefficients. Returned only when ``rlm_out=True``.
        rlm_results_t_dict : dict, optional
            Dictionary mapping each dependent-variable name to its regression
            t-statistics. Returned only when ``rlm_out=True``.

        Notes
        -----
        An intercept is automatically added to the predictors using
        :func:`statsmodels.api.add_constant`.

        The function applies FDR correction using ``method="indep"`` and
        ``alpha=0.05``.

        The function currently extracts ``p_b1`` and ``p_b4`` using fixed
        positions (1 and 7) in the flattened corrected p-value array. These
        indices therefore depend on the ordering and number of predictors in
        ``exog_array`` and the ordering of variables in ``endog``.
        """

    p_vals = []
    rlm_results_dict = {}
    rlm_results_t_dict = {}
    p_vals_dict = {}
    fdr_p_vals = []
    for i in range(len(endog)):
        endog_curr = df[endog[i]].values
        exog_curr = df[exog_array]
        exog_curr = sm.add_constant(exog_curr)

        rlm_model = sm.RLM(endog_curr, exog_curr, M=sm.robust.norms.HuberT())
        rlm_results = rlm_model.fit()
        p_vals.append(rlm_results.pvalues)

        rlm_results_dict[endog[i]] = rlm_results.params
        rlm_results_t_dict[endog[i]] = rlm_results.tvalues
        p_vals_dict[endog[i]] = rlm_results.pvalues



    #Apply fdr regression on pvals
    p_vals = np.array(p_vals)
    p_vals_flat = p_vals.flatten()
    p_conc_fdr = sm.stats.fdrcorrection(p_vals_flat, alpha=0.05, method='indep', is_sorted=False)
    p_corrected = np.round(p_conc_fdr[1], 3)

    # extract pvals for p_b1 and p_b4
    p_b1 = p_corrected[1]
    p_b4 = p_corrected[7]
    print('uncorrected_pvals are:', p_vals)

    if (rlm_out):
        return (p_corrected,p_b1, p_b4, rlm_results_dict, rlm_results_t_dict)
    else:
        return (p_corrected,p_b1, p_b4)

# Helper function to create subplots
def create_subplots(fig, gridspec, positions):
    """
         Helper function to create subplots to a figure at specified GridSpec positions.
        Parameters
        ----------
        fig : matplotlib.figure.Figure
            Figure to which the subplots will be added.
        gridspec : matplotlib.gridspec.GridSpec
            GridSpec defining the layout and positions available for the
            subplots.
        positions : sequence of int
            Indices of the GridSpec positions at which to create the subplots.

        Returns
        -------
        axes : list of matplotlib.axes.Axes
            List of axes corresponding to the requested GridSpec positions.
        """

    axes = [plt.Subplot(fig, gridspec[pos]) for pos in positions]
    for ax in axes:
        fig.add_subplot(ax)
    return axes
